"""Remove campos de garantia_calibracao_reutilizavel de ItemAta

Revision ID: 2abfed847f6b
Revises: 32a11389b47c
Create Date: 2025-06-01 15:32:36.595148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abfed847f6b'
down_revision = '32a11389b47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_ata', schema=None) as batch_op:
        batch_op.drop_column('reutilizavel')
        batch_op.drop_column('requer_calibracao')
        batch_op.drop_column('data_garantia_fim')
        batch_op.drop_column('proxima_calibracao')
        batch_op.drop_column('ultima_calibracao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_ata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_calibracao', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('proxima_calibracao', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('data_garantia_fim', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('requer_calibracao', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('reutilizavel', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
