"""Corrige importacao em forms e continua ajuste Contrato

Revision ID: 32a11389b47c
Revises: 6df067cc0e14
Create Date: 2025-05-30 14:20:22.926327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a11389b47c'
down_revision = '6df067cc0e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('unidade_medida', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('valor_total_item', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], name='fk_itemcontrato_contrato_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('consumo_item_contrato')
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contrato_ata_id'), type_='foreignkey')
        batch_op.drop_column('ata_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ata_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_contrato_ata_id'), 'ata', ['ata_id'], ['id'])

    op.create_table('consumo_item_contrato',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contrato_id', sa.INTEGER(), nullable=False),
    sa.Column('item_ata_id', sa.INTEGER(), nullable=False),
    sa.Column('quantidade_contratada', sa.FLOAT(), nullable=False),
    sa.Column('valor_unitario_contratado', sa.FLOAT(), nullable=True),
    sa.Column('valor_total_item_contratado', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], name=op.f('fk_consumoitemcontrato_contrato_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_ata_id'], ['item_ata.id'], name=op.f('fk_consumoitemcontrato_item_ata_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item_contrato')
    # ### end Alembic commands ###
