"""Adiciona tabela de logs de atividade

Revision ID: 3838e312d49f
Revises: 0d93e7e5d575
Create Date: 2025-06-07 14:25:44.717396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3838e312d49f'
down_revision = '0d93e7e5d575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_timestamp'))

    op.drop_table('log')
    # ### end Alembic commands ###
