"""Adiciona tabela e funcionalidade de Comentarios

Revision ID: 46aa4cf28b77
Revises: 3838e312d49f
Create Date: 2025-06-07 14:58:45.061953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46aa4cf28b77'
down_revision = '3838e312d49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commentable_id', sa.Integer(), nullable=False),
    sa.Column('commentable_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comentario_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comentario_timestamp'))

    op.drop_table('comentario')
    # ### end Alembic commands ###
