"""Criacao inicial de todas as tabelas com estrutura completa

Revision ID: 6df067cc0e14
Revises: 
Create Date: 2025-05-30 12:13:52.393322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df067cc0e14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_ata', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.Column('data_validade', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_ata')
    )
    op.create_table('unidade_saude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_unidade', sa.String(length=150), nullable=False),
    sa.Column('tipo_unidade', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email_responsavel', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_unidade')
    )
    op.create_table('contratinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_contratinho', sa.String(length=100), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('data_fim_vigencia', sa.DateTime(), nullable=True),
    sa.Column('favorecido', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ata_id', sa.Integer(), nullable=False),
    sa.Column('unidade_saude_id', sa.Integer(), nullable=True),
    sa.Column('valor_total_itens', sa.Float(), nullable=True),
    sa.Column('valor_total_manual', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ata_id'], ['ata.id'], name='fk_contratinho_ata_id'),
    sa.ForeignKeyConstraint(['unidade_saude_id'], ['unidade_saude.id'], name='fk_contratinho_unidade_saude_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.String(length=100), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('valor_global_contrato', sa.Float(), nullable=False),
    sa.Column('fornecedor', sa.String(length=200), nullable=True),
    sa.Column('data_assinatura_contrato', sa.DateTime(), nullable=True),
    sa.Column('data_inicio_vigencia', sa.DateTime(), nullable=True),
    sa.Column('data_fim_vigencia', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ata_id', sa.Integer(), nullable=True),
    sa.Column('valor_total_itens', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ata_id'], ['ata.id'], name='fk_contrato_ata_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_contrato')
    )
    op.create_table('empenho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_empenho', sa.String(length=100), nullable=False),
    sa.Column('descricao_simples', sa.Text(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('favorecido', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ata_id', sa.Integer(), nullable=False),
    sa.Column('unidade_saude_id', sa.Integer(), nullable=True),
    sa.Column('valor_total_itens', sa.Float(), nullable=True),
    sa.Column('valor_total_manual', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ata_id'], ['ata.id'], name='fk_empenho_ata_id'),
    sa.ForeignKeyConstraint(['unidade_saude_id'], ['unidade_saude.id'], name='fk_empenho_unidade_saude_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_ata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao_item', sa.String(length=255), nullable=False),
    sa.Column('unidade_medida', sa.String(length=50), nullable=True),
    sa.Column('quantidade_registrada', sa.Float(), nullable=False),
    sa.Column('saldo_disponivel', sa.Float(), nullable=False),
    sa.Column('valor_unitario_registrado', sa.Float(), nullable=True),
    sa.Column('lote', sa.String(length=100), nullable=True),
    sa.Column('tipo_item', sa.String(length=50), nullable=False),
    sa.Column('data_garantia_fim', sa.DateTime(), nullable=True),
    sa.Column('requer_calibracao', sa.Boolean(), nullable=True),
    sa.Column('ultima_calibracao', sa.DateTime(), nullable=True),
    sa.Column('proxima_calibracao', sa.DateTime(), nullable=True),
    sa.Column('reutilizavel', sa.Boolean(), nullable=True),
    sa.Column('ata_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ata_id'], ['ata.id'], name='fk_itemata_ata_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumo_item_contratinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contratinho_id', sa.Integer(), nullable=False),
    sa.Column('item_ata_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_consumida', sa.Float(), nullable=False),
    sa.Column('valor_unitario_no_consumo', sa.Float(), nullable=True),
    sa.Column('valor_total_consumido_item', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contratinho_id'], ['contratinho.id'], name='fk_consumoitemcontratinho_contratinho_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_ata_id'], ['item_ata.id'], name='fk_consumoitemcontratinho_item_ata_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumo_item_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('item_ata_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_contratada', sa.Float(), nullable=False),
    sa.Column('valor_unitario_contratado', sa.Float(), nullable=True),
    sa.Column('valor_total_item_contratado', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], name='fk_consumoitemcontrato_contrato_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_ata_id'], ['item_ata.id'], name='fk_consumoitemcontrato_item_ata_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumo_item_empenho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empenho_id', sa.Integer(), nullable=False),
    sa.Column('item_ata_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_consumida', sa.Float(), nullable=False),
    sa.Column('valor_unitario_no_consumo', sa.Float(), nullable=True),
    sa.Column('valor_total_consumido_item', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empenho_id'], ['empenho.id'], name='fk_consumoitemempenho_empenho_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_ata_id'], ['item_ata.id'], name='fk_consumoitemempenho_item_ata_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumo_item_empenho')
    op.drop_table('consumo_item_contrato')
    op.drop_table('consumo_item_contratinho')
    op.drop_table('item_ata')
    op.drop_table('empenho')
    op.drop_table('contrato')
    op.drop_table('contratinho')
    op.drop_table('unidade_saude')
    op.drop_table('ata')
    # ### end Alembic commands ###
